import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";

// Resolve __dirname (not available in ESM by default)
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load .env file from project root
dotenv.config({ path: path.resolve(__dirname, "../../.env") });

// Destructure env variables with defaults
const {
    MONGO_URI,
    DB_NAME,
    PORT = 5000,
    CORS_ORIGIN = "*",
    ACCESS_TOKEN_SECRET,
    ACCESS_TOKEN_EXPIRY = "1d",
    REFRESH_TOKEN_SECRET,
    REFRESH_TOKEN_EXPIRY = "7d",
    OPENAI_API_KEY,
    SENDER_ID,
    TEMPLATE_ID,
    RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET,

    // admin credential ======================
    ADMIN_FIRST_NAME,
    ADMIN_LAST_NAME,
    ADMIN_PHONE_NO,
    ADMIN_EMAIL,
    ADMIN_BLOOD_GROUP,
    ADMIN_PINCODE,
    ADMIN_PASSWORD,
    ADMIN_ADDRESS,

    // firebase user =========================
    FIREBASE_TYPE,
    FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY_ID,
    FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID,
    FIREBASE_AUTH_URI,
    FIREBASE_TOKEN_URI,
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    FIREBASE_CLIENT_X509_CERT_URL,
    FIREBASE_UNIVERSE_DOMAIN,
    // firebase venture =========================
    VENTURE_FIREBASE_TYPE,
    VENTURE_FIREBASE_PROJECT_ID,
    VENTURE_FIREBASE_PRIVATE_KEY_ID,
    VENTURE_FIREBASE_PRIVATE_KEY,
    VENTURE_FIREBASE_CLIENT_EMAIL,
    VENTURE_FIREBASE_CLIENT_ID,
    VENTURE_FIREBASE_AUTH_URI,
    VENTURE_FIREBASE_TOKEN_URI,
    VENTURE_FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    VENTURE_FIREBASE_CLIENT_X509_CERT_URL,
    VENTURE_FIREBASE_UNIVERSE_DOMAIN
} = process.env;

// Export as config object
export default {
    MONGO_URI,
    DB_NAME,
    PORT,
    CORS_ORIGIN,
    ACCESS_TOKEN_SECRET,
    ACCESS_TOKEN_EXPIRY,
    REFRESH_TOKEN_SECRET,
    REFRESH_TOKEN_EXPIRY,
    OPENAI_API_KEY,
    SENDER_ID,
    TEMPLATE_ID,
    RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET,

    // admin credential ======================
    ADMIN_FIRST_NAME,
    ADMIN_LAST_NAME,
    ADMIN_PHONE_NO,
    ADMIN_EMAIL,
    ADMIN_BLOOD_GROUP,
    ADMIN_PINCODE,
    ADMIN_PASSWORD,
    ADMIN_ADDRESS,

    // firebase =========================
    FIREBASE_TYPE,
    FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY_ID,
    FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID,
    FIREBASE_AUTH_URI,
    FIREBASE_TOKEN_URI,
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    FIREBASE_CLIENT_X509_CERT_URL,
    FIREBASE_UNIVERSE_DOMAIN,

    // firebase venture =========================
    VENTURE_FIREBASE_TYPE,
    VENTURE_FIREBASE_PROJECT_ID,
    VENTURE_FIREBASE_PRIVATE_KEY_ID,
    VENTURE_FIREBASE_PRIVATE_KEY,
    VENTURE_FIREBASE_CLIENT_EMAIL,
    VENTURE_FIREBASE_CLIENT_ID,
    VENTURE_FIREBASE_AUTH_URI,
    VENTURE_FIREBASE_TOKEN_URI,
    VENTURE_FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
    VENTURE_FIREBASE_CLIENT_X509_CERT_URL,
    VENTURE_FIREBASE_UNIVERSE_DOMAIN
};
